title: Eyram Attipoe # your name (or website title) here
logo: "/images/attipoe.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Eyram Attipoe is a budding broadcast journalist and voice over artiste. Eyram has worked with a few media institutions in the past years and notable among them is Media General's Adesa Productions Limited (APL). APL unearthed her writing skills by working on a few writing projects. She was also part of the 2018 Ghana's Most Beautiful (GMB) production team. Eyram's working experience taught her that hardwork, teamwork and good communication skills is key in every institution. She is a movie fanatic and a lover of table tennis. She has a degree in Communication Studies (Journalism).
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
